version: 0.0
os: linux
files:
  - source: overseer.war
    destination: /entropyshift/codedeploy/overseer
  - source: configure_http_port.xsl
    destination: /entropyshift/codedeploy/overseer
hooks:
  ApplicationStop:
    - location: stop_application
      timeout: 300
  ApplicationStart:
    - location: start_application
      timeout: 300