version: 0.0
os: linux
files:
  - source: overseer.war
    destination: /entropyshift/codedeploy/overseer
  - source: configure_http_port.xsl
    destination: /entropyshift/codedeploy/overseer
hooks:
  ApplicationStop:
    - location: sudo sh ./stop_application.sh
      timeout: 300
  ApplicationStart:
    - location: sudo sh ./start_application.sh
      timeout: 300
  BeforeInstall:
    - location: sudo rm -rf /entropyshift/codedeploy/overseer/*
      timeout: 300