version: 0.1

environment_variables:
  plaintext:
    AUTHOR: "CHAITANYA_MEESALA"

phases:
  pre_build:
    commands:
      - echo Pre-build started on `date`
      - echo Nothing to do on Pre-build phase as of now.
  build:
    commands:
      - echo build started on `date`
      - echo `mvn -version`
      - sudo wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo
      - sudo sed -i s/\$releasever/6/g /etc/yum.repos.d/epel-apache-maven.repo
      - sudo yum update -y apache-maven
      - sudo mvn install
  post_build:
    commands:
      - echo build completed on `date`
artifacts:
  files:
    - target/overseer.war
    - scripts/*
    - appspec.yml
  discard-paths: yes