version: 0.1

environment_variables:
  plaintext:
    AUTHOR: "CHAITANYA_MEESALA"

phases:
  pre_build:
    commands:
      - echo Pre-build started on `date`
      - echo Nothing to do on Pre-build phase as of now.
  build:
    commands:
      - echo build started on `date`
      - echo `java -version`
      - echo `mvn -version`
      - mvn install
  post_build:
    commands:
      - echo build completed on `date`
artifacts:
  files:
    - appspec.yml
    - target/overseer.war
    - scripts/*
  discard-paths: yes